=== AliouGN224/CabinetInfirmier/data/xsd/cabinet.xsd
<?xml version="1.1" encoding="UTF-8" ?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:medical="http://www.univ-grenoble-alpes.fr/l3miage/medical"
        targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/medical"
        elementFormDefault="qualified"
>
    <include schemaLocation="actes.xsd"/>

    <!-- Declaration de la racine-->
    <element name="cabinet" type="medical:Cabinet">
        <keyref name="intervenantExiste" refer="medical:idUnique">
            <selector xpath="medical:patients/medical:patient/medical:visite"/>
            <field xpath="@intervenant"/>
        </keyref>
    </element>

    <!-- Le type cabinet-->

    <complexType name="Cabinet">
        <sequence>
            <element name="nom" type="string"/>
            <element name="adresse" type="medical:Adresse"/>
            <element name="infirmiers" type="medical:Infirmiers">
                <key name="idUnique">
                    <selector xpath="medical:infirmier"/>
                    <field xpath="@id"/>
                </key>
            </element>
            <element name="patients" type="medical:Patients">
                <key name="numeroUnique">
                    <selector xpath="medical:patient"/>
                    <field xpath="medical:numero"/>
                </key>
            </element>
        </sequence>
    </complexType>

    <!-- le type liste Patients -->

    <complexType name="Patients">
        <sequence>
            <element name= 'patient' type="medical:Patient" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!-- le type  Patient -->

    <complexType name="Patient">
        <sequence>
            <element name="numero" type="medical:NumeroSecuriteScocial"/>
            <element name="nom" type="string"/>
            <element name="prenom" type="string"/>
            <element name="sexe" type="medical:SexeType"/>
            <element name="naissance" type="date"/>
            <element name="adresse" type="medical:Adresse"/>
            <element name="visite" type="medical:Visite" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!-- le type  Visite -->
    <complexType name="Visite">
        <sequence>
            <element name="acte" type="medical:Acte" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="date" type="date"/>
        <attribute name="intervenant" type="string"/>
    </complexType>

    <!-- le type Acte -->

    <complexType name="Acte">
        <attribute name="id" type="string"/>
    </complexType>

    <!-- le type Adresse -->

    <complexType name="Adresse">
        <sequence>
            <element name="etage" type="integer" minOccurs="0"/>
            <element name="numero" type="integer" minOccurs="0"/>
            <element name="rue" type="string"/>
            <element name="codePostal" type="medical:CodePostal"/>
            <element name="ville" type="string"/>
        </sequence>
    </complexType>

    <!-- le type liste Infirmiers -->

    <complexType name="Infirmiers">
        <sequence>
            <element name="infirmier" type="medical:Infirmier" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>


    <!-- le type  Infrimier -->

    <complexType name="Infirmier">
        <sequence>
            <element name="nom" type="string"/>
            <element name="prenom" type="string"/>
            <element name="photo" type="string"/>
        </sequence>
        <attribute name="id" type="string"/>
    </complexType>

    <!-- le type CodePostal -->
    <simpleType name="CodePostal">
        <restriction base="string">
            <pattern value="\d{5}"/>
        </restriction>
    </simpleType>

    <!-- le type  Numéro sécurité social -->
    <simpleType name="NumeroSecuriteScocial">
        <restriction base="string">
            <pattern value="[1-4]\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-9]\d|2A|2B|99)(0\d{2}|[1-9]\d{2}){2}\d{2}"/>
        </restriction>
    </simpleType>

    <!-- Le type SexeType -->

    <simpleType name="SexeType">
        <restriction base="string">
            <enumeration value="F"/>
            <enumeration value="M"/>
        </restriction>
    </simpleType>
</schema>

=== AliouGN224/CabinetInfirmier/data/xml/infirmiers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<infirmiers  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical"
             xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/medical ../xsd/cabinet.xsd">
    <infirmier id="001">
        <nom>Fréchie</nom>
        <prenom>Sarah</prenom>
        <photo>sarah.png</photo>
    </infirmier>
    <infirmier id="002">
        <nom>Stické</nom>
        <prenom>Sophie</prenom>
        <photo>sophie.png</photo>
    </infirmier>
    <infirmier id="003">
        <nom>Ochon</nom>
        <prenom>Paul</prenom>
        <photo>paul.png</photo>
    </infirmier>
</infirmiers>
